enum errno {
    E_UNSPECIFIED = 1,
    E_NO_ENT,
    E_ID_DIR,
    E_NOT_DIR,
    E_INVALID_ARG,
    E_TOO_MANY_FILES,
    E_TOO_MANY_FILE_DESCRIPTORS,
    E_ILLEGAL_FILE_DESCRIPTOR,
    E_TRY_AGAIN,
};
